language: node_js
node_js:
  - "8.10.0"

before_install:
  - npm install --prefix packages/spark-core
  - npm install --prefix packages/spark-highlight-board
install:
  - npm test --prefix packages/spark-core
  - npm test --prefix packages/spark-highlight-board
