language: node_js
node_js:
  - "8.10.0"

before_install:
  - npm install --prefix packages/spark-core
  - npm install --prefix packages/spark-highlight-board
script:
  - cd packages/spark-core && npm test && cd ..
  - cd spark-highlight-board && npm test
