language: node_js
node_js:
  - "8.10.0"

jobs:
  include:
    - stage: spark-core
      install:
        - npm install --prefix packages/spark-core
      script:
        - cd packages/spark-core && npm test
    - stage: spark-highlight-board
      install:
        - npm install --prefix packages/spark-highlight-board
      script:
        - cd packages/spark-highlight-board && npm test
