language: node_js
node_js:
  - "8.10.0"

jobs:
  include:
    - stage: installation
      install:
        - npm install --prefix packages/spark-core
      install:
        - npm install --prefix packages/spark-highlight-board
    - stage: unit tests
      script:
        - cd packages/spark-core && npm test
      script:
        - cd packages/spark-highlight-board && npm test
